[character]
symbol = "â¯"
error_symbol = "âœ—"
use_symbol_for_status = true

[cmd_duration]
min_time = 0.5

[git_status]
conflicted = "âŒ"
ahead = "ğŸš—ğŸ’¨"
behind = "ğŸ’¦"
diverged = "ğŸ˜µ"
untracked = "ğŸ¤·"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = "âœ…"
renamed = "ğŸ‘…"
deleted = "ğŸ—‘ï¸"
